version: 2

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo build step
      - run: npm install
      - run: npm audit fix
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - run: curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
      - persist_to_workspace:
          root: ~/public
          paths: .

  test:
    docker:
      - image: alpine:latest
    working_directory: ~/public
    steps:
      - run: grep -q "Gatsby" ./public/index.html
      - persist_to_workspace:
          root: ~/public
          paths: .

  deploy:
    docker:
      - image: node:latest
    working_directory: ~/public
    steps:
      - run: echo deploy step
      - run: npm install --global surge
      - run: surge --project ./public --domain Lambu.surge.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
