version: 2

jobs:

  build:
    docker:
      - image: docker:latest
    environment:
      - IMAGE_NAME: nginx-v
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run: echo $HOME
      - run: echo "$DOCKER_PASSWD" | docker login --username $DOCKER_USER --password-stdin docker.io
      - run: docker build  -t $IMAGE_NAME$CIRCLE_BUILD_NUM .
      - run: docker tag $IMAGE_NAME$CIRCLE_BUILD_NUM $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM
      - run: docker push $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM

  test:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.06.0-ce
      - run: docker pull $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM
      - run: docker run -d --name testapp $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM
      - run: docker exec testapp curl --retry 10 --retry-connrefused http://localhost:80/public/index.html

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
           requires:
             - build

