version: 2

jobs:
  build:
    docker:
      - image: docker:latest
    environment:
      - IMAGE_NAME: nginx-v
    steps:
      - checkout
      - setup_remote_docker:
          #docker_layer_caching: true
      - run: echo $HOME
      - run: echo "$DOCKER_PASSWD" | docker login --username $DOCKER_USER --password-stdin docker.io
      - run: docker build  -t $IMAGE_NAME$CIRCLE_BUILD_NUM .
      - run: docker tag $IMAGE_NAME$CIRCLE_BUILD_NUM $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM
      - run: docker push $DOCKER_USER/$IMAGE_NAME$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
