version: 2

jobs:
  build:
    docker:
      - image: docker:latest
    environment:
      - IMAGE_NAME: nginx-v
    steps:
      - checkout
      - setup_remote_docker:
          #docker_layer_caching: true
      - run: echo $HOME
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWD docker.io
      - run: docker build  -t $IMAGE_NAME$CIRCLE_BUILD_NUM .
      - run: docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME
      - run: docker push $DOCKER_USER/$IMAGE_NAME

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
